service: estate-id-api
frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1
  apiGateway:
    shouldStartNameWithService: true
  environment:
    ZOOM: ${self:custom.zoomLevel}
    INCREMENTP_VERIFICATION_API_ENDPOINT: ${env:INCREMENTP_VERIFICATION_API_ENDPOINT}
    INCREMENTP_VERIFICATION_API_KEY: ${env:INCREMENTP_VERIFICATION_API_KEY}
    AWS_DYNAMODB_API_KEY_TABLE_NAME: ${self:custom.awsDynamodbApiKeyTableName}

custom:
  # ID will be changed If other zoom specified.
  zoomLevel: 24
  awsDynamodbApiKeyTableName: estate-id-api-key-${self:provider.stage}

package:
  exclude:
    - __tests__
    - .*
    - src
    - package.json
    - README.md
    - serverless.yml
    - tsconfig.json
    - yarn.lock
    - package-lock.json

resources:
  Resources:
    apiKeyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.apiKeyTableName}
        AttributeDefinitions:
          - AttributeName: apiKey
            AttributeType: S
        KeySchema:
          - AttributeName: apiKey
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  public:
    handler: dist/public.handler
    events:
      - http:
          path: '/'
          method: get
          integration: lambda-proxy

  authenticated:
    handler: dist/authenticated.handler
    events:
      - http:
          path: '/'
          method: get
          integration: lambda-proxy
