service: estate-id-api
frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1
  apiGateway:
    shouldStartNameWithService: true
  environment:
    ZOOM: ${self:custom.zoomLevel}

custom:
  # ID will be changed If other zoom specified.
  zoomLevel: 24

package:
 exclude:
    - __tests__
   - .*
   - src
   - package.json
   - README.md
   - serverless.yml
   - tsconfig.json
   - yarn.lock
   - package-lock.json

functions:
  public:
    handler: dist/public.handler
    events:
      - http:
          path: '/'
          method: get
          integration: lambda-proxy

